### ISSUE TITLE
invalid version: latest

### ISSUE THREAD

**Issue by juliangruber** [electron/update.electronjs.org#47]
If someone doesn't pass a valid semver, we currently 500:

```
May 15 03:07:31 electron-update-server app/web.1:  {"level":50,"time":1526378850822,"msg":"Invalid Version: latest","pid":4,"hostname":"c853bc29-6768-4c53-a420-b78389ba2d65","type":"Error","stack":"TypeError: Invalid Version: latest\n    at new SemVer (/app/node_modules/semver/semver.js:305:11)\n    at compare (/app/node_modules/semver/semver.js:578:39)\n    at Function.eq (/app/node_modules/semver/semver.js:617:10)\n    at Updates.handleUpdate (/app/index.js:76:23)\n    at <anonymous>","v":1} 
May 15 03:07:31 electron-update-server app/web.1:  {"level":30,"time":1526378850823,"msg":"request","pid":4,"hostname":"c853bc29-6768-4c53-a420-b78389ba2d65","method":"GET","url":"/forCandies/GooglePhotosDesktop/darwin/latest","status":500,"ipHash":"ff84d3a0139a554efdc1f6f963aa18aefc053b2db7a54e75d368036466137cc2","duration":95,"v":1} 
```

**Comment by juliangruber** [comment]
cc @davidherzina, you need to pass the currently installed app's version as last parameter
